
CREATE TABLE EQUIPO(
IdEquipo INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(50) NOT NULL,
Pais CHAR(3) NOT NULL,
Estado CHAR(1) CHECK(Estado in ('A', 'I')),
FechaCreacion DATE NOT NULL,
);

CREATE TABLE ESTADO(
IdEstado INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Descripion VARCHAR(50) NOT NULL,
FechaCreacion DATE NOT NULL
);

CREATE TABLE JUGADORES(
IdJugadores INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(100) NOT NULL,
Apellido VARCHAR(100) NOT NULL,
FechaNacimiento DATE NOT NULL,
Pasaporte VARCHAR(9) NOT NULL,
Direccion VARCHAR(200) NOT NULL,
Sexo CHAR(1) CHECK(Sexo in ('M', 'F')),
IdEquipo INT NOT NULL,
IdEstado INT NOT NULL,
CONSTRAINT FK_EQUIPO FOREIGN KEY(IdEquipo) REFERENCES EQUIPO(IdEquipo),
CONSTRAINT FK_ESTADO FOREIGN KEY(IdEstado) REFERENCES ESTADO(IdEstado)
);

SELECT * FROM EQUIPO;
SELECT * FROM ESTADO;
SELECT * FROM JUGADORES;


SELECT EQ.IdEquipo, EQ.NOMBRE, JUGA.Nombre FROM EQUIPO EQ INNER JOIN JUGADORES JUGA ON EQ.IdEquipo = JUGA.IdEquipo WHERE EQ.NOMBRE = 'Boston';